"""
Mapeo canónico de columnas XLSX → nombres internos.
Los archivos octubre usan prefijo 'F600_', nov/dic usan '600_'.
Ambos tienen las mismas 109 columnas con los mismos nombres.
"""

DECLARACION_COLS = {
    "C1ANNIO": "anio",
    "C4NUMFORMULARIO": "num_formulario",
    "C6DV": "dv",
    "C11RAZONSOCIALEXPORTAD": "razon_social_exportador",
    "C18NUMIDENTIFEXPORT": "nit_exportador",
    "C25 NMERO DOCUMENTO IDENTIFIC": "nit_declarante",
    "C31RAZONSOCIALDECL": "razon_social_declarante",
    "C38RAZONSOCIAL": "razon_social_destinatario",
    "C39DOMICILIODESTINATARIO": "domicilio_destinatario",
    "C40CIUDAD": "ciudad_destinatario",
    "C41 CLASE DUA EXPORTACIONES": "clase_dua",
    "C43 TIPO DILIGENCIAMIENTO": "tipo_diligenciamiento",
    "C44 TIPO DESPACHO": "tipo_despacho",
    "C49 RGIMEN ADUANERO": "regimen_aduanero",
    "C50 CD. ADUANA DESPACHO": "cod_aduana_despacho",
    "COD INT PAIS TRAMITE C51": "cod_pais_tramite",
    "C52 CD. REGIN PROCEDENCI": "cod_region_procedencia",
    "C54 CD. TIPO EMBARQUE": "tipo_embarque",
    "C56 CD. INCOTERMS": "incoterms",
    "C57 LUGAR ENTREGA": "lugar_entrega",
    "C58 CD. MONEDA TRANSACCIN": "moneda_transaccion",
    "C59 VALOR FACTURA MONEDA TRANS": "valor_factura_moneda",
    "C60 TASA CAMBIO": "tasa_cambio",
    "C67 CD. MODO TRANSPORTE": "modo_transporte",
    "C68 CD. TIPO CARGA": "tipo_carga",
    "C69 CD. ADUANA SALIDA": "cod_aduana_salida",
    "C70 CD. PAS DESTINO FINAL": "pais_destino",
    "COD INT PAIS DESTINO FINAL C70": "cod_pais_destino",
    "C71 CD. LUGAR DESTINO FINAL": "lugar_destino",
    "C72 VALOR TOTAL FOB U$": "valor_fob_usd",
    "C73 VALOR TOTAL FLETES U$": "valor_fletes_usd",
    "C74 VALOR TOTAL SEGUROS U$": "valor_seguros_usd",
    "C75 VALOR TOTAL OTROS GASTOS U": "valor_otros_gastos_usd",
    "C76 VALOR TOTAL EXPORTACIONES ": "valor_total_exportacion_usd",
    "C77 VALOR A REINTEGRAR U$": "valor_reintegrar_usd",
    "C78 TOTAL VALOR AGREGADO NACIO": "valor_agregado_nacional",
    "C79 TOTAL SERIES": "total_series",
    "C80 TOTAL NMERO BULTOS": "total_bultos",
    "C81 TOTAL PESO BRUTO KGS.": "total_peso_bruto_kg",
    "C83 FECHA ACEPTACIN": "fecha_aceptacion",
    "C85 FECHA AUTORIZACIN EMBARQU": "fecha_autorizacion_embarque",
}

SERIE_COLS = {
    "C4NUMFORMULARIO": "num_formulario",  # FK join key
    "C98 NO. SERIE": "num_serie",
    "IDE_NOMENCLATURA": "nomenclatura",
    "C99SUBPARTIDA": "subpartida",
    "C100 COD. COMPLEMENTARIO": "cod_complementario",
    "C102 COD. UNIDAD FSICA": "cod_unidad_fisica",
    "C103 CANTIDAD UNIDADES FSICAS": "cantidad_fisica",
    "C104 COD. UNIDAD COMERCIAL": "cod_unidad_comercial",
    "C105 CANTIDAD UNIDADES COMERCI": "cantidad_comercial",
    "C106 COD. CLASE EMBALAJE": "cod_clase_embalaje",
    "C107 NO. BULTOS": "num_bultos",
    "C108 PESO BRUTO KGS.": "peso_bruto_kg",
    "C109 PESO NETO KGS.": "peso_neto_kg",
    "C110 VALOR FOB U$": "valor_fob_usd",
    "C111 MARCAS": "marcas",
    "C112 DESCRIPCION": "descripcion",
    "C115 COD. PAS ORIGEN": "cod_pais_origen",
    "C116 COD. REGIN ORIGEN": "cod_region_origen",
}
